version: '3'
services:
  node:
    build: https://github.com/robertocjunior/Wa-GLPI-Bot.git
    command: "npm run start"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - whatsapp_session:/home/node/app/whatsapp_session_data
    restart: unless-stopped

volumes:
  whatsapp_session:
